#A file to store all view related constants, like button sizes
SINGLE_ELEMENT_DIV=0

SMALL_ELEMENT_DIV=5
MEDIUM_ELEMENT_DIV=10
LARGE_ELEMENT_DIV=20

#Button sizes
LARGE_BTN_WIDTH=300
LARGE_BTN_HEIGHT=50
MEDIUM_BTN_WIDTH=250
MEDIUM_BTN_HEIGHT=30
SMALL_BTN_WIDTH=100
SMALL_BTN_HEIGHT=20

#App colors
BACKGROUND_COLOR="#C5C5BF"
TEXT_COLOR="#1A1A1A"
BUTTON_COLOR="#F3A6A6"
BUTTON_HOVER_COLOR="#DA0000"
SELECTED_COLOR="#CC02FF"
BUTTON_DISABLED_COLOR="#727272"
CHAT_BACKGROUND="#EFEFC4"

#Panel sizes
PANEL_X=150
PANEL_Y=200
WIDE_PANEL=400
ELEMS_FOR_SCROLLBAR=2
